describe('load homepage', () => {
  it('checks toolbar bar contents', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('button#clearProgramDlg').should('exist')
    cy.get('button#saveProgram').should('exist')
    cy.get('button#toggleSaveAs').should('exist')
    cy.get('button#loadProgramList').should('exist')
    cy.get('button#runProgram').should('exist')
    cy.get('button#getProgramCode').should('exist')
    cy.get('button#exportProgram').should('exist')
    cy.get('button#pickFile').should('exist')
  })

  it('checks blockly loaded', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('.blocklyTotal').should('exist')
    cy.get('.blocklyToolboxDiv').should('exist')
    cy.get('.blocklyWorkspace').should('exist')
  })

  it('loads an existing program', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('button#loadProgramList').should('exist')
    cy.get('button#loadProgramList').click()
    cy.contains('test_sonars').should('exist')
    cy.contains('test_sonars').click()
    cy.get('.blocklyPath').should('exist')
    cy.get('button#clearProgramDlg').click()
    cy.get('button.text-green').should('exist')
    cy.get('button.text-green').click()
  })

  it('create a new program, save it', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('.blocklyToolboxContents').find('#blockly-1').click({ force: true })
    cy.get('.blocklyDraggable').click({ force: true, multiple: true })
    cy.get('button#saveProgram').click()
    cy.get('#card_program_name_must_be_filled').find('.ok').click()
    cy.get('#card_program_save_as').find('#program_save_as_name').type('test_program_new')
    cy.get('#card_program_save_as').find('.ok').click()
    cy.get('button#clearProgramDlg').click()
    cy.get('#card_clear_workspace').find('.ok').click()
    // cy.get('.blocklyPath').should('not.exist')
    cy.get('button#loadProgramList').click()
    cy.get('#card_program_list').find('.v-list').scrollTo('bottom')
    cy.contains('test_program_new').click()
    cy.get('.blocklyPath').should('exist')
    cy.get('button#clearProgramDlg').click()
    cy.get('#card_clear_workspace').find('.ok').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_program_new').parents('.v-list-item').find('.mdi-delete').click({ force: true })
    cy.get('#card_program_delete_confirm').find('.ok').click()
    // cy.get('button#loadProgramList').click()
    // cy.contains('test_program_new').should('not.exist')
  })  

  it('create a new program, save as new', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('.blocklyToolboxContents').find('#blockly-1').click({ force: true })
    cy.get('.blocklyDraggable').click({ force: true, multiple: true })
    cy.get('button#toggleSaveAs').click()
    cy.get('#card_program_save_as').find('#program_save_as_name').type('test_program_new')
    cy.get('#card_program_save_as').find('.ok').click()
    cy.get('button#clearProgramDlg').click()
    cy.get('#card_clear_workspace').find('.ok').click()
    // cy.get('.blocklyPath').should('not.exist')
    cy.get('button#loadProgramList').click()
    cy.get('#card_program_list').find('.v-list').scrollTo('bottom')
    cy.contains('test_program_new').click()
    cy.get('.blocklyPath').should('exist')
    cy.get('button#clearProgramDlg').click()
    cy.get('#card_clear_workspace').find('.ok').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_program_new').parents('.v-list-item').find('.mdi-delete').click({ force: true })
    cy.get('#card_program_delete_confirm').find('.ok').click()
    // cy.get('button#loadProgramList').click()
    // cy.contains('test_program_new').should('not.exist')
  })  

  it('create a new program, save as existing, verify check confirm', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('.blocklyToolboxContents').find('#blockly-1').click({ force: true })
    cy.get('.blocklyDraggable').click({ force: true, multiple: true })
    cy.get('button#toggleSaveAs').click()
    cy.get('#card_program_save_as').find('#program_save_as_name').type('test_program_new')
    cy.get('#card_program_save_as').find('.ok').click()
    cy.get('button#toggleSaveAs').click()
    cy.get('#card_program_save_as').find('#program_save_as_name').clear().type('test_program_new')
    cy.get('#card_program_save_as').find('.ok').click()
    cy.get('#card_program_overwrite').find('.ok').click()
    cy.get('button#loadProgramList').click()
    cy.get('#card_program_list').find('.v-list').scrollTo('bottom')
    cy.contains('test_program_new').click()
    cy.get('.blocklyPath').should('exist')
    cy.get('button#clearProgramDlg').click()
    cy.get('#card_clear_workspace').find('.ok').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_program_new').parents('.v-list-item').find('.mdi-delete').click({ force: true })
    cy.get('#card_program_delete_confirm').find('.ok').click()
  })  

  it('create a new program, save as existing default, verify not possible', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').should('exist')
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('.blocklyToolboxContents').find('#blockly-1').click({ force: true })
    cy.get('.blocklyDraggable').click({ force: true, multiple: true })
    cy.get('button#toggleSaveAs').click()
    cy.get('#card_program_save_as').find('#program_save_as_name').type('test_sonars')
    cy.get('#card_program_save_as').find('.ok').click()
    cy.get('#card_program_overwrite').find('.ok').click()
    cy.get('#card_program_overwrite_cannot').should('exist')
    cy.get('#card_program_overwrite_cannot').find('.ok').click()
  })  

  it('load an existing program, run, stop, delete', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_sonars').click()
    cy.get('button#runProgram').click()
    cy.get('#card_program_runtime').should('exist')
    cy.get('#card_program_runtime').find('img').should('exist')
    cy.get('#card_program_runtime').find('.stop').click()
  })  

  it('load a program, show code', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_sonars').click()
    cy.get('button#getProgramCode').click()
    cy.get('#card_program_code').should('exist')
    cy.get('#card_program_code').find('.ok').click()
  })

  it('load a program, export', () => {
    cy.visit('http://localhost:8080')
    cy.get('.v-carousel').should('exist')
    cy.get('button.v-app-bar-nav-icon').should('exist').click()
    cy.get('a.v-list-item[href*="/program"]').click()
    cy.get('#app').click()
    cy.get('button#loadProgramList').click()
    cy.contains('test_sonars').click()
    cy.get('button#exportProgram').click()
  })  
})