/* tslint:disable */
/* eslint-disable */
/**
 * CoderBot Cloud API - Robot only - OpenAPI 3.0
 * CoderBot Cloud API - Robot only
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@coderbot.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

