const defaultActivity = {
	"stock":true,
	"default":true,
	"uiLang":null,
	"defaultView":null,
	"exec":{
			"camera":true,
			"log":true
	},
	"name":"default",
	"drawerEnabled":true,
	"showName":true,
	"buttons":[
			{
				"action":"clearProgramDlg",
				"icon":"clear",
				"label":"message.activity_program_clear",
				"type":"text"
			},
			{
				"action":"saveProgram",
				"icon":"save",
				"label":"message.activity_program_save",
				"type":"text"
			},
			{
				"action":"toggleSaveAs",
				"icon":"edit",
				"label":"message.activity_program_save_as",
				"type":"text"
			},
			{
				"action":"loadProgramList",
				"icon":"folder_open",
				"label":"message.activity_program_load",
				"type":"text"
			},
			{
				"action":"runProgram",
				"icon":"play_arrow",
				"label":"message.activity_program_run",
				"type":"text"
			},
			{
				"action":"getProgramCode",
				"icon":"code",
				"label":"message.activity_program_show_code",
				"type":"text"
			},
			{
				"action":"exportProgram",
				"icon":"fa-file-export",
				"label":"message.activity_program_export",
				"type":"text"
			},
			{
				"action":"pickFile",
				"icon":"fa-file-import",
				"label":"message.activity_program_import",
				"type":"text"
			}
	],
	"description":"",
	"fontSize":"Medio",
	"capsSwitch":true,
	"bodyFont":"Roboto",
	"codeFont":"ubuntumono",
	"maxBlocks":0,
	"availableViews":[
			
	],
	"viewSource":null,
	"autoRecVideo":null,
	"toolbox": null
}
